# Uptime Monitoring Configuration for Token Sentiment Bot
# This file configures health checks and monitoring endpoints

# Health Check Endpoints
health_checks:
  # Basic health check (returns OK/UNHEALTHY)
  basic:
    url: "/health"
    method: "GET"
    expected_status: 200
    expected_response: "OK"
    timeout_seconds: 10
    interval_seconds: 60
    
  # Readiness check (returns READY/NOT_READY)
  readiness:
    url: "/ready"
    method: "GET"
    expected_status: 200
    expected_response: "READY"
    timeout_seconds: 10
    interval_seconds: 30
    
  # Detailed metrics endpoint
  metrics:
    url: "/metrics"
    method: "GET"
    expected_status: 200
    timeout_seconds: 15
    interval_seconds: 300  # 5 minutes
    
  # Root endpoint for basic service info
  root:
    url: "/"
    method: "GET"
    expected_status: 200
    timeout_seconds: 10
    interval_seconds: 120  # 2 minutes

# Alerting Configuration
alerts:
  # Response time thresholds
  response_time:
    warning_threshold_ms: 5000   # 5 seconds
    critical_threshold_ms: 10000 # 10 seconds
    
  # Uptime thresholds
  uptime:
    warning_threshold_percent: 95.0
    critical_threshold_percent: 90.0
    
  # Memory usage thresholds
  memory:
    warning_threshold_mb: 400
    critical_threshold_mb: 500
    
  # Error rate thresholds
  error_rate:
    warning_threshold_percent: 5.0
    critical_threshold_percent: 10.0

# Monitoring Services Configuration
monitoring_services:
  # UptimeRobot (Free tier)
  uptimerobot:
    enabled: true
    check_interval_minutes: 5
    endpoints:
      - name: "Token Sentiment Bot Health"
        url: "https://your-domain.com/health"
        type: "http"
        
  # Pingdom (Free tier)
  pingdom:
    enabled: false
    check_interval_minutes: 1
    endpoints:
      - name: "Token Sentiment Bot"
        url: "https://your-domain.com/health"
        
  # StatusCake (Free tier)
  statuscake:
    enabled: false
    check_interval_minutes: 5
    endpoints:
      - name: "Token Sentiment Bot"
        url: "https://your-domain.com/health"

# Notification Settings
notifications:
  # Email notifications
  email:
    enabled: false
    recipients: []
    smtp_server: ""
    smtp_port: 587
    
  # Slack notifications
  slack:
    enabled: false
    webhook_url: ""
    channel: "#alerts"
    
  # Telegram notifications
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""

# Performance Monitoring
performance:
  # Response time tracking
  response_time:
    enabled: true
    sample_rate: 0.1  # 10% of requests
    
  # Memory monitoring
  memory:
    enabled: true
    check_interval_seconds: 60
    
  # Rate limiting monitoring
  rate_limiting:
    enabled: true
    check_interval_seconds: 30
    
  # Cache performance
  cache:
    enabled: true
    check_interval_seconds: 300  # 5 minutes

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/monitoring.log"
  max_size_mb: 10
  backup_count: 5 